os: linux
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

jobs:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer update
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text
