sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer install
  - phpenv rehash

script:
  - phpunit --coverage-text
